### ISSUE TITLE
CakePHP 5 Support

### ISSUE THREAD

**Issue by mixable** [mirko-pagliai/cakephp-database-backup#97] opened 2023-10-19 11:19 UTC
Currently, this plugin requires `"cakephp/cakephp": "^4.0"`. Any plans to support the latest version of CakePHP 5?

Thank you!

**Comment by mirko-pagliai** [comment] 2023-10-19 11:23
HIi @mixable ,

yes, I will do it in the next few days, first for CakePHP 4.5, then for CakePHP 5.

Please remember to donate to this project if you appreciate it.

**Comment by mirko-pagliai** [comment] 2023-10-23 16:25
The problem is more complex than it seems.
CakePHP requires at least PHP 8.1 and PHPUnit 10.
This creates more of a problem with many dependencies, which still support PHP 7.2/7.4 and PHPUnit 9, including some of my packages (so I should start with those first).

It is something that will be done, but it is not so immediate and it is not so obvious or banal. I would say that for now, for projects that use other dependencies related to CakePHP, it is not the case to immediately upgrade to version 5.

**Comment by mirko-pagliai** [comment] 2023-10-24 21:42
Created [cakephp-5.x branch](https://github.com/mirko-pagliai/cakephp-database-backup/tree/cakephp-5.x).

A release will be released later, as I would like to make some more updates.

**Comment by mixable** [comment] 2024-01-03 20:56
@mirko-pagliai thank you for the CakePHP 5 branch. I was not able to fully upgrade my project to CakePHP 5 and test your changes yet. Currently, the bottleneck are some other packages that still do not support CakePHP 5. I will give you some feedback as soon as I tested your changes.

**Comment by mirko-pagliai** [comment] 2024-01-03 21:37
@mixable It seems quite normal to me. In my opinion you are trying to upgrade a little too soon, especially if your project requires several dependencies. It takes time and patience.

**Closed** 2024-01-03 21:38 UTC
Labels: enhancement
